---
title: "R Notebook"
output: html_notebook
---


```{r}

#pc.modelA.v1 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/Nominal/modelA_pc_gamFit.rds')
#pc.modelA.v2 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/BMI_FIX/modelA_pc_gamFit.rds')
pc.modelA.v3 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/QCOVID_FIX2/modelA_pc_gamFit.rds')
#pc.modelA.v4 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/VACCINE_FIX/modelA_pc_gamFit.rds')
#pc.modelA.v4 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/QCOVID_FIX2/modelA_pc_gamFit.rds')
pc.modelA.v5 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/QCOVID_OLD/modelA_pc_gamFit.rds')

pc.modelB.v3 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/QCOVID_FIX2/modelB_pc_gamFit.rds')
pc.modelB.v5 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/QCOVID_OLD/modelB_pc_gamFit.rds')



#bd.modelA.v1 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/Nominal/modelA_bd_gamFit.rds')
#bd.modelA.v2 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/BMI_FIX/modelA_bd_gamFit.rds')
#bd.modelA.v3 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/QCOVID_FIX/modelA_bd_gamFit.rds')
#bd.modelA.v4 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/VACCINE_FIX/modelA_bd_gamFit.rds')
#bd.modelA.v4 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/QCOVID_OLD/modelA_bd_gamFit.rds')
```

```{r}
map <- c('0'='0','1'='1','2'='2','3'='3-4','4'='5+','5'='Unknown')
fix_risks <- function(df){
  df <- df %>% mutate(level = ifelse(var=='n_risk_gps' & pos>1,map[as.character(level)],level))
  return (df);
}


#pc.modelA.v1.or <- eavehelpers::get_or_from_gam(pc.modelA.v1) %>% fix_risks
#pc.modelA.v2.or <- eavehelpers::get_or_from_gam(pc.modelA.v2) %>% fix_risks
pc.modelA.v3.or <- eavehelpers::get_or_from_gam(pc.modelA.v3) %>% fix_risks
#pc.modelA.v4.or <- eavehelpers::get_or_from_gam(pc.modelA.v4) %>% fix_risks
pc.modelA.v5.or <- eavehelpers::get_or_from_gam(pc.modelA.v5) %>% fix_risks

pc.modelB.v3.or <- eavehelpers::get_or_from_gam(pc.modelB.v3) %>% fix_risks
pc.modelB.v5.or <- eavehelpers::get_or_from_gam(pc.modelB.v5) %>% fix_risks


#bd.modelA.v1.or <- eavehelpers::get_or_from_gam(bd.modelA.v1) %>% fix_risks
#bd.modelA.v2.or <- eavehelpers::get_or_from_gam(bd.modelA.v2) %>% fix_risks
#bd.modelA.v3.or <- eavehelpers::get_or_from_gam(bd.modelA.v3) %>% fix_risks
#bd.modelA.v4.or <- eavehelpers::get_or_from_gam(bd.modelA.v4) %>% fix_risks

```

```{r}
eavehelpers::display_ratios_table(pc.modelA.v1.or %>% rename(Nominal=OR))
```


```{r}
eavehelpers::display_ratios_table(pc.modelA.v2.or %>% rename(Nominal=OR))
```

```{r}
eavehelpers::display_ratios_table(pc.modelA.v3.or %>% rename(Nominal=OR))
```

```{r,fig.height = 11, fig.width = 11}
eavehelpers::display_ratios_table(pc.modelB.v3.or %>% rename(Nominal=OR)  %>% mutate(
                           level=ifelse(grepl("Q_DIAG",names) & level=='Yes',label,level),
                           label=ifelse(grepl("Q_DIAG",names),'QCOVID',label))
                           %>% filter(label=='QCOVID' & pos>1))
```

```{r}
eavehelpers::display_ratios_table(pc.modelB.v5.or %>% rename(Nominal=OR)  %>% mutate(
                           level=ifelse(grepl("Q_DIAG",names) & level=='Yes',label,level),
                           label=ifelse(grepl("Q_DIAG",names),'QCOVID',label))
                           %>% filter(label=='QCOVID' & pos>1))
```

```{r}
eavehelpers::display_ratios_table(bd.modelA.v4.or %>% rename(Nominal=OR))
```


```{r,fig.height = 9, fig.width = 11}
#temp <- pc.modelA.v1.or %>% mutate(dataset='Nominal') %>% rbind(pc.modelA.v2.or %>% mutate(dataset='BMI Fix')) %>%
#         rbind(pc.modelA.v3.or %>% mutate(dataset='QCOVID Fix')) %>%
#         rbind(pc.modelA.v4.or %>% mutate(dataset='Vaccine Fix'))
temp <- pc.modelA.v3.or %>% mutate(dataset='Feb22') %>% rbind(pc.modelA.v5.or %>% mutate(dataset='Old')) 
eavehelpers::plot_ratios(temp %>% rename(Nominal=OR) %>% 
                            mutate(
                           level=ifelse(grepl("Q_DIAG",names) & level=='Yes',label,level),
                           label=ifelse(grepl("Q_DIAG",names),'QCOVID',label)
                         ),
                         fill=cohort,
                         facet=as.factor(label) ~ relevel(as.factor(dataset),ref='Feb22')
)

```


```{r,fig.height =11, fig.width = 11}
temp <- pc.modelB.v3.or %>% mutate(dataset='Feb22') %>% rbind(pc.modelB.v5.or %>% mutate(dataset='Old')) 
eavehelpers::plot_ratios(temp %>% rename(Nominal=OR) %>% 
                            mutate(
                           level=ifelse(grepl("Q_DIAG",names) & level=='Yes',label,level),
                           label=ifelse(grepl("Q_DIAG",names),'QCOVID',label)
                         ),
                         fill=cohort,
                         facet=as.factor(label) ~ relevel(as.factor(dataset),ref='Feb22')
)
```






```{r}
pc.modelD.v1 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/Nominal/modelE_cox_HR.rds')
pc.modelD.v2 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/VACCINE_FIX/modelE_cox_HR.rds')
pc.modelD.v3 <- readRDS('/home/calumm09/SerologyAnalysis/analysis/results/QCOVID_OLD/modelE_cox_HR.rds')
pc.modelD.v3
```


```{r,fig.height=9,fig.width=10}
temp <- pc.modelD.v1 %>% mutate(Nominal=estimate,LCL=conf.low,UCL=conf.high,label=name, dataset='Feb22') %>%
           rbind(
             pc.modelD.v3 %>% mutate(Nominal=estimate,LCL=conf.low,UCL=conf.high,label=name, dataset='Old')
           )

eavehelpers::plot_ratios(temp,
                         xmin=0.1,xmax=10,
                         xtitle='HR (95% CI)',
                         fill=dataset,
                         facet=as.factor(name) ~ fct_rev(as.factor(dataset)))
```

```{r}
eavehelpers::display_ratios_table( pc.modelD.v1 %>% mutate(Nominal=estimate,LCL=conf.low,UCL=conf.high,label=name))
```

```{r}
eavehelpers::display_ratios_table( pc.modelD.v2 %>% mutate(Nominal=estimate,LCL=conf.low,UCL=conf.high,label=name))
```




```{r}
d1 <- readRDS("/conf/EAVE/GPanalysis/data/temp/fail_to_mount_pc_Jan10_v1.rds")
d2 <- readRDS("/conf/EAVE/GPanalysis/data/temp/fail_to_mount_pc_Jan10_v3.rds")
nrow(d1)
nrow(d2)
```



```{r}
df1 <- eavehelpers::serology_outcome_analysis.create_hosp_death_dataframe(d1,eave.data) %>% code_vars()
df2 <- eavehelpers::serology_outcome_analysis.create_hosp_death_dataframe(d2,eave.data) %>% code_vars()

nrow(df1)
nrow(df2)
```

```{r}
df1 %>% filter(outcome_hosp==1) %>% group_by(stage) %>% summarise(n=n())
```
```{r}
df2 %>% filter(outcome_hosp==1) %>% group_by(stage) %>% summarise(n=n())
```






```{r,fig.height = 9, fig.width = 11}
temp <- bd.modelA.v1.or %>% mutate(dataset='Nominal') %>% rbind(bd.modelA.v2.or %>% mutate(dataset='BMI Fix')) %>%
         rbind(bd.modelA.v3.or %>% mutate(dataset='QCOVID Fix'))
eavehelpers::plot_ratios(temp %>% rename(Nominal=OR),
                         fill=cohort,
                         facet=as.factor(label) ~ relevel(as.factor(dataset),ref='Nominal')
)

```

